### ISSUE TITLE
failed WebSocket connection message when trying to use chat

### ISSUE THREAD

**Issue by jdwilkin4** [nickytonline/astro-partykit-starter#9] opened 2023-12-31 01:29 UTC
**Describe the bug**
I tried using the chat by logging into a room with a username and when I go to that page, it won't submit a message. When I open up the console these are the messages displaying. 

<img width="1507" alt="Screenshot 2023-12-30 at 5 26 18 PM" src="https://github.com/nickytonline/astro-partykit-starter/assets/67210629/af3e8c40-ead6-42fb-aee7-29ff8f4e06a7">

**To Reproduce**

1. Go to https://astro-partykit-react-starter.netlify.app/
2. Join room 1 with username of your choosing
3. try to input a message and click on the button
4. Open up the console to see the failed websocket error messages 

**Expected behavior**
 I should be able to send a message

**Screenshots**
see screenshot above

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nickytonline** [comment] 2023-12-31 02:33
Thanks for reporting this @jdwilkin4! The code is all good. The issue is that the Partykit portion of the site is not deployed.

I encountered this while working on a project that uses this template.

I'll get the partykit deployment sorted once I'm back from snowboarding.

Also, if you'd like to be a maintainer, I'd love to have you on the team! No pressure though.

**Comment by nickytonline** [comment] 2023-12-31 04:08
I've fixed the deploy but I still need to add the Partykit deployment as part of the deploy of the site.

Closing this as completed as the bug no longer occurs. I will create a separate issue for adding partykit to the deployment.

**Closed by nickytonline** 2023-12-31 04:08 UTC
Labels: bug, needs triage

**Comment by jdwilkin4** [comment] 2023-12-31 08:11
> Also, if you'd like to be a maintainer, I'd love to have you on the team! No pressure, though.

Love to be on the team 😄
